#########################################
#  Educational Cloud Platform Service   #
#    Computer Engineering, KMITL        #
#########################################

version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ce-cloud-api
    container_name: ce-cloud-api
    env_file: .env
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    networks:
      - ce-cloud-network
    ports:
      - "3001:3001"
    volumes:
      - api-data:/usr/src/app
    depends_on:
      - db

  db:
    image: citusdata/citus:11.2-alpine
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - ce-cloud-network
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
  api-data:

networks:
  ce-cloud-network:
